// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Wallet;

#nullable disable

namespace Wallet.Migrations
{
    [DbContext(typeof(WalletDbContext))]
    [Migration("20260620100404_WalletAccountingFixes")]
    partial class WalletAccountingFixes
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("wallet")
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Wallet.WalletAccount", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<long>("Balance")
                        .HasColumnType("bigint");

                    b.Property<long>("Frozen")
                        .HasColumnType("bigint");

                    b.HasKey("UserId");

                    b.ToTable("accounts", "wallet", t =>
                        {
                            t.HasCheckConstraint("ck_balance_non_negative", "\"Balance\" >= 0");
                        });
                });

            modelBuilder.Entity("Wallet.WalletHold", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<long>("Amount")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("PurchaseId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ReleasedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("WalletId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("IdempotencyKey")
                        .IsUnique()
                        .HasDatabaseName("uq_holds_idempotency_key");

                    b.HasIndex("PurchaseId")
                        .HasDatabaseName("idx_holds_purchase");

                    b.HasIndex("WalletId", "Status")
                        .HasDatabaseName("idx_holds_wallet");

                    b.ToTable("wallet_holds", "wallet", t =>
                        {
                            t.HasCheckConstraint("ck_holds_amount_non_negative", "\"Amount\" >= 0");
                        });
                });

            modelBuilder.Entity("Wallet.WalletLedger", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<long>("Amount")
                        .HasColumnType("bigint");

                    b.Property<long>("BalanceAfter")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("WalletId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("IdempotencyKey")
                        .IsUnique()
                        .HasDatabaseName("uq_ledger_idempotency_key");

                    b.HasIndex("WalletId", "CreatedAt")
                        .HasDatabaseName("idx_ledger_wallet");

                    b.ToTable("ledger_entries", "wallet", t =>
                        {
                            t.HasCheckConstraint("ck_ledger_amount_non_negative", "\"Amount\" >= 0");
                        });
                });

            modelBuilder.Entity("Wallet.WalletHold", b =>
                {
                    b.HasOne("Wallet.WalletAccount", "Wallet")
                        .WithMany()
                        .HasForeignKey("WalletId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Wallet");
                });

            modelBuilder.Entity("Wallet.WalletLedger", b =>
                {
                    b.HasOne("Wallet.WalletAccount", "Wallet")
                        .WithMany()
                        .HasForeignKey("WalletId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Wallet");
                });
#pragma warning restore 612, 618
        }
    }
}
